---
title: "writing_functions"
author: "ww2745"
date: "2024-10-24"
output: github_document
---
```{r}
library(tidyverse)
library(rvest)
library(readxl)
set.seed(1)

```


##writing my first function

as an example, here's a z-score computation.

```{r}
x_vec= rnorm(n=25, mean=10, sd=3.5)

(x_vec - mean(x_vec))/ sd(x_vec)
```

Now i'll write a function to do this.
```{r}
z_scores=function(x){
  
  if (!is.numeric(x)){
    stop("x needs to be numeric")
  }
  
  if (length(x)<5){
    stop("you need at least 5 numbers to compute z scores")
  }
  
  z= (x-mean(x))/sd(x)
  
  return(z)
}

z_scores(x=x_vec)
```

does this always work?
```{r, error=TRUE}
z_scores(x=3)
z_scores(x=c("My","name","is"))
```

## A new function!

```{r}
mean_and_sd = function(x){
  mean_x=mean(x)
  sd_x=sd(x)
  
  out_df=
    tibble(
      mean=mean_x,
      sd=sd_x
    )
  
  return(out_df)
}

mean_and_sd(x_vec)
```

## Check stuff using a simulation

```{r}
sim_df=
  tibble(
    x=rnorm(30,10,5)
  )

sim_df |> 
  summarize(
    mean=mean(x),
    sd=sd(x)
  )
```

Simulation function to check sample mean and sd.

```{r}
sim_mean_sd = function(sample_size=30, true_mean=10, true_sd=2){
  sim_df=
  tibble(
    x=rnorm(sample_size,true_mean,true_sd)
  )

 out_df =
  sim_df |> 
  summarize(
    mean=mean(x),
    sd=sd(x)
  )
  
  return(out_df)
}

sim_mean_sd(sample_size=30, true_mean=4, true_sd =12) ##can rewrite default num
sim_mean_sd()
```

## Revists
```{r}
lotr_import = function(cell_range, movie_title){
  movie_df=
    read_excel("data/LotR_Words.xlsx", range=cell_range) |> 
    mutate(movie="movie_title") |> 
    janitor::clean_names() |> 
    pivot_longer(
      female:male,
      names_to ="sex",
      values_to = "words"
    ) |> 
    select(movie,everything())
  
  return(movie_df)
}

lotr_df=
  bind_rows(
    lotr_import("B3:D6","fellowship"),
    lotr_import("F3:H6","two_towers"),
    lotr_import("J3:L6","return_king")
  )
```


## NSDUH
```{r}
nsduh_url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm" ##put outside the function because each time the function would download from html

nsduh_html = read_html(nsduh_url)

drug_import=function(name, num_table,html){
  drug_df=
    nsduh_html |>  ##looking outside the function body, add into input
    html_table() |> 
    nth(num_table) |> 
    slice(-1) |> 
    mutate(drug ="name") |> 
    select(-contains("P Value"))
  
  return(drug_df)
}

bind_rows(
  drug_import(html=nsduh_html,"marj",1),
  drug_import(html=nsduh_html,"cocaine",5)
  
)

```

do this instead:
dont need to see this function in r file,
use for many rmd
source